### TItle of the topic : Memory Cohort
### Source:Prof. MD data sets
### It has been used to get the interpretation of the age in the real life

In [15]:
import pandas as pd
import numpy as np
data = pd.read_csv("memory_cohort_group_project.csv")

In [16]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2119 entries, 0 to 2118
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   participant_id          2119 non-null   str
 1   visit                   2119 non-null   int64
 2   visit_date              2119 non-null   str
 3   age                     2119 non-null   float64
 4   sex                     2119 non-null   str
 5   education_years         2119 non-null   str
 6   apoe4_carrier           2119 non-null   str
 7   hypertension            2119 non-null   str
 8   bmi                     2013 non-null   float64
 9   mmse                    2119 non-null   int64
 10  moca                    1949 non-null   float64
 11  cdr                     2119 non-null   float64
 12  hippocampal_volume_mm3  1907 non-null   float64
 13  diagnosis               2119 non-null   str
dtypes: float64(5), int64(2), str(7)
memory usage: 300.8 KB

In [17]:
data.head()

,participant_id,visit,visit_date,age,sex,education_years,apoe4_carrier,hypertension,bmi,mmse,moca,cdr,hippocampal_volume_mm3,diagnosis
0,DC5000,1,2017-10-31,71.0,Male,12,No,No,23.8,29,28.0,0.0,3773.0,Healthy
1,DC5000,2,2019-04-19,72.5,Male,12,No,No,27.3,29,27.0,0.0,3780.0,Normal
2,DC5000,3,2020-08-09,73.8,Male,12,No,No,26.1,28,26.0,0.0,3785.0,Normal
3,DC5000,4,2022-08-18,75.8,Male,12,No,No,28.1,27,NaN,0.0,3627.0,Normal
4,DC5001,1,2016-02-20,75.0,Male,13 years,No,No,24.0,27,23.0,0.0,4127.0,Normal

In [18]:
data.tail()

,participant_id,visit,visit_date,age,sex,education_years,apoe4_carrier,hypertension,bmi,mmse,moca,cdr,hippocampal_volume_mm3,diagnosis
2114,DC5598,4,2021-01-20,72.6,Female,7,No,No,28.4,20,20.0,1.0,3251.00,Dementia
2115,DC5599,1,2017-01-13,75.0,Male,8,No,No,27.5,28,24.0,0.0,3755.00,Normal
2116,DC5599,2,2018-08-21,76.6,Male,8,No,No,NaN,28,25.0,0.0,3631.00,Normal
2117,DC5599,3,2020-02-29,78.1,Male,8,No,No,29.1,28,24.0,0.0,3.76,Normal
2118,DC5599,4,2021-08-06,79.6,Male,8,No,No,25.6,27,24.0,0.0,3649.00,Normal

In [19]:
data.shape

(2119, 14)

In [21]:
print("Number of rows and columns:", data.shape)

Number of rows and columns: (2119, 14)

In [38]:
data.columns.tolist()

['participant_id',
 'visit',
 'visit_date',
 'age',
 'sex',
 'education_years',
 'apoe4_carrier',
 'hypertension',
 'bmi',
 'mmse',
 'moca',
 'cdr',
 'hippocampal_volume_mm3',
 'diagnosis']

In [39]:
print(data.dtypes)

participant_id                str
visit                       int64
visit_date                    str
age                       float64
sex                           str
education_years               str
apoe4_carrier                 str
hypertension                  str
bmi                       float64
mmse                        int64
moca                      float64
cdr                       float64
hippocampal_volume_mm3    float64
diagnosis                     str
dtype: object

In [40]:
print(data.select_dtypes(include="number").columns.tolist())

['visit', 'age', 'bmi', 'mmse', 'moca', 'cdr', 'hippocampal_volume_mm3']

In [41]:
print(data.select_dtypes(include="str").columns.tolist())

['participant_id', 'visit_date', 'sex', 'education_years', 'apoe4_carrier', 'hypertension', 'diagnosis']

In [42]:
print(data.select_dtypes(include="category").columns.tolist())

[]

In [43]:
data.describe()

,visit,age,bmi,mmse,moca,cdr,hippocampal_volume_mm3
count,2119.000000,2119.000000,2013.000000,2119.000000,1949.000000,2119.000000,1907.000000
mean,2.438886,75.048655,26.598609,26.305805,23.669574,0.255545,3258.776460
std,1.236797,7.744646,4.094721,3.540127,3.266343,0.338630,1255.101301
min,1.000000,60.000000,13.500000,3.000000,1.000000,0.000000,2.840000
25%,1.000000,68.350000,23.800000,25.000000,22.000000,0.000000,3378.500000
50%,2.000000,75.600000,26.700000,27.000000,24.000000,0.000000,3669.000000
75%,3.000000,81.600000,29.300000,28.000000,26.000000,0.500000,3906.500000
max,5.000000,91.000000,40.400000,59.000000,30.000000,2.000000,4857.000000

In [44]:
print(data[data["mmse"] > 30][["participant_id", "mmse"]])
print(data[data["moca"] > 30][["participant_id", "moca"]])

     participant_id  mmse
485          DC5138    56
568          DC5164    55
606          DC5176    57
1425         DC5409    56
1562         DC5446    52
1736         DC5496    58
1926         DC5548    59
2099         DC5594    58
Empty DataFrame
Columns: [participant_id, moca]
Index: []